# Generated by Django 6.0.7 on 2026-08-29 14:47

from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    User.objects.filter(role__in=["hiring_manager", "candidate"]).update(role="recruiter")


def reverse_legacy_roles(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_avatar_url_user_avatar'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_roles, reverse_legacy_roles),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter')], default='recruiter', max_length=20),
        ),
    ]
